version: '3.10'

x-settings: &global
  environment:
    - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    - SECRET_KEY=${SECRET_KEY}
    - DEBUG=${DEBUG}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - PGDATA=${PGDATA}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}

services:
  api:
    container_name: api
    command: gunicorn dfa_test.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    build:
      context: .
      dockerfile: Dockerfile
    <<: *global
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global

  nginx:
    build: ./nginx
    volumes:
      - ./static:/var/www/stc/static
      - ./media:/var/www/stc/media
    ports:
      - "80:80"
    depends_on:
      - api


volumes:
  postgres_data: